version : '3'
services:
  mantap:
    build: ./php
    image: mantap_php:latest
    container_name: mantap
    hostname: "mantap"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - database_31
  database_31:
    image: mariadb:10.2
    container_name: database_31
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: djambred
      MYSQL_PASSWORD: pemweb123!.
      MYSQL_ROOT_PASSWORD: pemweb123
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql  
  nginx_pemweb:
    build: ./nginx
    image: nginx_pemweb_3:latest
    container_name: nginx_pemweb_3
    hostname: "nginx_pemweb_3"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mantap